[project]
name = 'Digital-Pickup-Basketball-Game'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.pickup-basketball]
path = 'contracts/pickup-basketball.clar'
clarity_version = 3
epoch = 3.1

[contracts.player-matching]
path = 'contracts/player-matching.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
